apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    # - image: us.gcr.io/ticketing-dev-392611/auth
    - image: dongquannguyen/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: dongquannguyen/client
      context: client
      sync:
        manual:
          - src: /**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: dongquannguyen/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: dongquannguyen/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-392611
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}